In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model
data = pd.read_csv(r"F:\0_个人学习\3_数据分析与挖掘\4_机器学习\2_线性回归\longley.csv")
data

Unnamed: 0  GNP.deflator      GNP  Unemployed  Armed.Forces  Population  \
0         1947          83.0  234.289       235.6         159.0     107.608   
1         1948          88.5  259.426       232.5         145.6     108.632   
2         1949          88.2  258.054       368.2         161.6     109.773   
3         1950          89.5  284.599       335.1         165.0     110.929   
4         1951          96.2  328.975       209.9         309.9     112.075   
5         1952          98.1  346.999       193.2         359.4     113.270   
6         1953          99.0  365.385       187.0         354.7     115.094   
7         1954         100.0  363.112       357.8         335.0     116.219   
8         1955         101.2  397.469       290.4         304.8     117.388   
9         1956         104.6  419.180       282.2         285.7     118.734   
10        1957         108.4  442.769       293.6         279.8     120.445   
11        1958         110.8  444.546       468.1         263.7     121.950   
12        1959         112.6  482.704       381.3         255.2     123.366   
13        1960         114.2  502.601       393.1         251.4     125.368   
14        1961         115.7  518.173       480.6         257.2     127.852   
15        1962         116.9  554.894       400.7         282.7     130.081   

    Year  Employed  
0   1947    60.323  
1   1948    61.122  
2   1949    60.171  
3   1950    61.187  
4   1951    63.221  
5   1952    63.639  
6   1953    64.989  
7   1954    63.761  
8   1955    66.019  
9   1956    67.857  
10  1957    68.169  
11  1958    66.513  
12  1959    68.655  
13  1960    69.564  
14  1961    69.331  
15  1962    70.551

In [21]:
x = np.array(data[:][['GNP','Unemployed','Armed.Forces','Population','Year','Employed']])
y = np.array(data[:]['GNP.deflator'])
print(x)
print(y)

[[ 234.289  235.6    159.     107.608 1947.      60.323]
 [ 259.426  232.5    145.6    108.632 1948.      61.122]
 [ 258.054  368.2    161.6    109.773 1949.      60.171]
 [ 284.599  335.1    165.     110.929 1950.      61.187]
 [ 328.975  209.9    309.9    112.075 1951.      63.221]
 [ 346.999  193.2    359.4    113.27  1952.      63.639]
 [ 365.385  187.     354.7    115.094 1953.      64.989]
 [ 363.112  357.8    335.     116.219 1954.      63.761]
 [ 397.469  290.4    304.8    117.388 1955.      66.019]
 [ 419.18   282.2    285.7    118.734 1956.      67.857]
 [ 442.769  293.6    279.8    120.445 1957.      68.169]
 [ 444.546  468.1    263.7    121.95  1958.      66.513]
 [ 482.704  381.3    255.2    123.366 1959.      68.655]
 [ 502.601  393.1    251.4    125.368 1960.      69.564]
 [ 518.173  480.6    257.2    127.852 1961.      69.331]
 [ 554.894  400.7    282.7    130.081 1962.      70.551]]
[ 83.   88.5  88.2  89.5  96.2  98.1  99.  100.  101.2 104.6 108.4 110.8
 112.6 114.2 1

In [22]:
# 创建模型
model = linear_model.LassoCV()
model.fit(x, y)
# lasso系数
print(model.alpha_)
# 相关系数
print(model.coef_)

14.134043936116361
[0.10093575 0.00586331 0.00599214 0.         0.         0.        ]


In [24]:
model.predict([x[-2]])

array([115.77558105])