In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import linear_model
data = pd.read_csv(r"F:\0_个人学习\3_数据分析与挖掘\4_机器学习\2_线性回归\longley.csv")
x = np.array(data[:][['GNP','Unemployed','Armed.Forces','Population','Year','Employed']])
y = np.array(data[:]['GNP.deflator'])
print(x)
print(y)

[[ 234.289  235.6    159.     107.608 1947.      60.323]
 [ 259.426  232.5    145.6    108.632 1948.      61.122]
 [ 258.054  368.2    161.6    109.773 1949.      60.171]
 [ 284.599  335.1    165.     110.929 1950.      61.187]
 [ 328.975  209.9    309.9    112.075 1951.      63.221]
 [ 346.999  193.2    359.4    113.27  1952.      63.639]
 [ 365.385  187.     354.7    115.094 1953.      64.989]
 [ 363.112  357.8    335.     116.219 1954.      63.761]
 [ 397.469  290.4    304.8    117.388 1955.      66.019]
 [ 419.18   282.2    285.7    118.734 1956.      67.857]
 [ 442.769  293.6    279.8    120.445 1957.      68.169]
 [ 444.546  468.1    263.7    121.95  1958.      66.513]
 [ 482.704  381.3    255.2    123.366 1959.      68.655]
 [ 502.601  393.1    251.4    125.368 1960.      69.564]
 [ 518.173  480.6    257.2    127.852 1961.      69.331]
 [ 554.894  400.7    282.7    130.081 1962.      70.551]]
[ 83.   88.5  88.2  89.5  96.2  98.1  99.  100.  101.2 104.6 108.4 110.8
 112.6 114.2 1

In [5]:
# 创建模型
model = linear_model.ElasticNetCV()
model.fit(x, y)

# 弹性网系数
print(model.alpha_)
# 相关系数
print(model.coef_)

30.310944054302677
[0.1006612  0.00589596 0.00593021 0.         0.         0.        ]


In [7]:
model.predict([x[-2]])

array([115.74523947])