In [33]:
import numpy as np
import operator
def createDataSet():
    group = np.array([[108,5],[115,8],[5,89],[1,101]])
    labels = ['动作片','动作片','爱情片','爱情片']
    return group,labels

In [34]:
#创建数据集
group, labels = createDataSet()
#打印数据集
print(group)
print(labels)
a = np.array([101,20])
b = ((group - np.tile(a,(4,1)))**2)
print(b)
c = b.sum(axis=1)
print(c)
d = c**0.5
print(d)
d.argsort()

[[108   5]
 [115   8]
 [  5  89]
 [  1 101]]
['动作片', '动作片', '爱情片', '爱情片']
[[   49   225]
 [  196   144]
 [ 9216  4761]
 [10000  6561]]
[  274   340 13977 16561]
[ 16.55294536  18.43908891 118.22436297 128.68954892]


array([0, 1, 2, 3], dtype=int64)

In [37]:
def classify0(inx,dataset,labels,k):
    # 获取数据的行数
    dataSetSize = dataset.shape[0]
    # 设计与dataset同样的行数（重复inx）
    new_inx = np.tile(inx,(dataSetSize,1))
    # 求取两个矩阵向量的差值
    diff = dataset - new_inx
    # 求取其平方值
    diffMat = diff ** 2
    # 将每行数据相加便于求距离，sum(0)列相加，sum(1)行相加
    sqDistances = diffMat.sum(axis=1)
    # 求取距离（开方求距离）
    distances = sqDistances**0.5
    #返回distances中元素从小到大排序后的索引值
    sortedDistIndices = distances.argsort()
    #定一个记录类别次数的字典
    classCount = {}
    for i in range(k):
        #取出前k个元素的类别
        voteIlabel = labels[sortedDistIndices[i]]
        print(voteIlabel)
        #计算类别次数
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    print(sortedClassCount)
    return sortedClassCount[0][0]

In [40]:
test = np.array([101,20])
group, labels = createDataSet()
movie_style = classify0(test, group, labels, 3)
print('需要判断的电影类型是：%s'% movie_style)

动作片
动作片
爱情片
[('动作片', 2), ('爱情片', 1)]
需要判断的电影类型是：动作片
